# Generated by Django 3.2.3 on 2024-08-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240815_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Кол-во ингридиента в рецепте', 'verbose_name_plural': 'Кол-во ингридиента в рецепте'},
        ),
    ]
