# Generated by Django 3.2.3 on 2024-08-13 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipeingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Ингредиентов не может быть меньше 1')], verbose_name='Количество'),
        ),
    ]
