# Generated by Django 3.2.3 on 2024-09-25 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240924_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingbyrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopp_recipe', to='recipes.recipe', verbose_name='Список покупок'),
        ),
    ]
