# Generated by Django 3.2.3 on 2024-08-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240815_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='subscription_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата подписки'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Аватар'),
        ),
    ]
